# Generated by Django 2.0.6 on 2019-08-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cate_name', models.CharField(blank=True, max_length=20, null=True)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('book_counts', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DOrderiterm',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('shop_num', models.CharField(blank=True, max_length=20, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('shop_id', models.IntegerField(blank=True, null=True)),
                ('order_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'd_orderiterm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TAddress',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('detail_address', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('telphone', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('addr_phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 't_address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TBook',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(blank=True, max_length=20, null=True)),
                ('author', models.CharField(blank=True, max_length=20, null=True)),
                ('original_cost', models.CharField(blank=True, max_length=20, null=True)),
                ('publisher', models.CharField(blank=True, max_length=20, null=True)),
                ('publish_time', models.DateField(blank=True, null=True)),
                ('publish_version', models.CharField(blank=True, max_length=20, null=True)),
                ('print_time', models.DateField(blank=True, null=True)),
                ('print_version', models.CharField(blank=True, max_length=20, null=True)),
                ('ibsn', models.CharField(blank=True, db_column='IBSN', max_length=20, null=True)),
                ('word_number', models.CharField(blank=True, max_length=20, null=True)),
                ('page_number', models.CharField(blank=True, max_length=20, null=True)),
                ('book_size', models.CharField(blank=True, max_length=20, null=True)),
                ('paper', models.CharField(blank=True, max_length=20, null=True)),
                ('package', models.CharField(blank=True, max_length=20, null=True)),
                ('author_intro', models.TextField(blank=True, null=True)),
                ('catalogue', models.TextField(blank=True, null=True)),
                ('media_comment', models.TextField(blank=True, null=True)),
                ('rel_price', models.CharField(blank=True, max_length=20, null=True)),
                ('editor_recommendation', models.TextField(blank=True, null=True)),
                ('content_introduction', models.TextField(blank=True, null=True)),
                ('digest_image_path', models.CharField(blank=True, max_length=2000, null=True)),
                ('product_image_path', models.CharField(blank=True, max_length=2000, null=True)),
                ('series_name', models.CharField(blank=True, max_length=128, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('shelves_date', models.DateField(blank=True, null=True)),
                ('customer_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('book_status', models.IntegerField(blank=True, null=True)),
                ('sales', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
            options={
                'db_table': 't_book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TOrder',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('num', models.CharField(blank=True, max_length=20, null=True)),
                ('create_date', models.DateTimeField()),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TShoppingCart',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('column_6', models.CharField(blank=True, db_column='Column_6', max_length=20, null=True)),
            ],
            options={
                'db_table': 't_shopping_cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('user_name', models.CharField(blank=True, max_length=30, null=True)),
                ('user_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
